## Arrays

Julia has provides a first-class multidimensional array implementation, with the optimizations you want/expect for homogeneous element types and the generality you want for heterogeneous types.

In [1]:
a = [10, 20, 30]

3-element Array{Int64,1}:
 10
 20
 30

In [2]:
 a = ["foo", "bar", 10]

3-element Array{Any,1}:
   "foo"
   "bar"
 10     

As you can see that the compiler has inferred the types of the arrays as `Int64` and `Any`. Also it indicated that they are 1 dimensional.

### Interpreting the properties of arrays : 

In [3]:
size(a)

(3,)

In [4]:
ndims(a)

1

As you can see above, the arrays are flat, i.e., there is only a single dimension in which there are 3 elements. We can also specify the type and construct an uninitialised array,

In [5]:
Array{Float64}(3)

3-element Array{Float64,1}:
 6.94063e-310
 6.94063e-310
 6.94063e-310

In [6]:
# To create an empty array of type Float64
Float64[]

0-element Array{Float64,1}

Or use functions which return special types of arrays, 

In [7]:
rand(10)

10-element Array{Float64,1}:
 0.756674
 0.170228
 0.13873 
 0.850179
 0.483059
 0.961794
 0.319195
 0.534104
 0.429598
 0.89293 

Note that by default rand() returns an Array with elements of type Float64 

In [8]:
eye(5)

5×5 Array{Float64,2}:
 1.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  1.0

In [9]:
diagm([1,2,3,4])

4×4 Array{Int64,2}:
 1  0  0  0
 0  2  0  0
 0  0  3  0
 0  0  0  4

### Arrays : Vectors or matrices

There are containers of type Vector and Matrix. Let us see what these are, and how they are derived from the general Array type

In [10]:
Array{Int64, 1} == Vector{Int64}

true

In [11]:
Array{Int64, 2} == Matrix{Int64}

true

In [12]:
Array{Int64, 1} == Matrix{Int64}

false

In [13]:
Array{Int64, 3} == Matrix{Int64}

false

Changing dimensions of Arrays can be done using the reshape() function,

In [14]:
a = [1, 2, 3, 4, 5, 6]

6-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6

In [15]:
b = reshape(a,3,2)

3×2 Array{Int64,2}:
 1  4
 2  5
 3  6

So the rule is if size(a) = k, then reshape(a, m, n) such that m * n = k.

In [16]:
reshape(a, 3, 1, 2)

3×1×2 Array{Int64,3}:
[:, :, 1] =
 1
 2
 3

[:, :, 2] =
 4
 5
 6

In [17]:
squeeze([1 2 3 4], 1)

4-element Array{Int64,1}:
 1
 2
 3
 4

### Indexing Arrays

In [18]:
a = rand(3,3)

3×3 Array{Float64,2}:
 0.14815   0.362191  0.375959
 0.601265  0.646944  0.123479
 0.548902  0.301976  0.954682

The above 3x3 Array appears to be a 2-dimensional array with 9 elements, but its actual representation is a view of a linear contiguous sequence of numbers in memory.

In [19]:
a = rand(1000,1000)
s1 = zero(eltype(a));
idx = eachindex(a)
@time for i in idx
    s1 += a[i]
end
(m,n)=size(a)

s2 = zero(eltype(a));
@time for i = 1:m, j=1:n
    s1 += a[i, j]
end

s3 = zero(eltype(a));
@time for j=1:n, i=1:m
    s1 += a[i, j]
end

  0.228011 seconds (5.00 M allocations: 91.538 MB, 6.78% gc time)
  0.235018 seconds (3.98 M allocations: 76.050 MB, 4.67% gc time)
  0.195407 seconds (3.98 M allocations: 76.050 MB, 3.57% gc time)


In [20]:
c = rand(6,4)

6×4 Array{Float64,2}:
 0.809715  0.906938  0.866851  0.63161 
 0.892301  0.20822   0.974566  0.821464
 0.896225  0.169436  0.574656  0.995962
 0.646919  0.131558  0.233104  0.696791
 0.709148  0.029673  0.60829   0.403691
 0.739534  0.577573  0.432523  0.180114

In [21]:
c[1:5, 1:2]

5×2 Array{Float64,2}:
 0.809715  0.906938
 0.892301  0.20822 
 0.896225  0.169436
 0.646919  0.131558
 0.709148  0.029673

Observe from the previous that Julia follows column-major ordering. Below experiment shows that Julia also stores in column-major order in memory. The time taken for accessing a column is faster than the time taken to access a row.

In [22]:
d = rand(10000, 10000)

10000×10000 Array{Float64,2}:
 0.513175   0.500608   0.849503   …  0.153758   0.692473   0.485299 
 0.919212   0.137022   0.99319       0.179675   0.259343   0.643476 
 0.713209   0.0338038  0.18991       0.452297   0.686225   0.0280247
 0.214868   0.235761   0.84322       0.916606   0.114845   0.504305 
 0.146415   0.845554   0.349069      0.140132   0.149511   0.0781155
 0.73894    0.364373   0.959224   …  0.92107    0.702068   0.220752 
 0.530185   0.117331   0.470929      0.281119   0.121219   0.973049 
 0.819535   0.79082    0.359337      0.904323   0.491946   0.319803 
 0.121214   0.648857   0.954916      0.0443461  0.967609   0.422846 
 0.405308   0.879169   0.137821      0.664398   0.0621123  0.0419013
 0.698912   0.706325   0.607528   …  0.43639    0.90264    0.172169 
 0.974207   0.212602   0.913448      0.0617644  0.0374892  0.210344 
 0.528297   0.70176    0.852064      0.375792   0.559119   0.398171 
 ⋮                                ⋱                                 
 0.9

In [23]:
@time slice = d[1:10000,1];
slice

  0.036369 seconds (18.74 k allocations: 907.297 KB)


10000-element Array{Float64,1}:
 0.513175 
 0.919212 
 0.713209 
 0.214868 
 0.146415 
 0.73894  
 0.530185 
 0.819535 
 0.121214 
 0.405308 
 0.698912 
 0.974207 
 0.528297 
 ⋮        
 0.906766 
 0.588949 
 0.683089 
 0.0852581
 0.601125 
 0.143029 
 0.0721053
 0.2072   
 0.970287 
 0.574868 
 0.800576 
 0.540503 

In [24]:
@time slice = d[1,1:10000];
slice

  0.033620 seconds (17.58 k allocations: 845.759 KB)


10000-element Array{Float64,1}:
 0.513175 
 0.500608 
 0.849503 
 0.97217  
 0.080729 
 0.607991 
 0.757213 
 0.44738  
 0.545359 
 0.89298  
 0.983727 
 0.457753 
 0.986804 
 ⋮        
 0.358249 
 0.340334 
 0.909409 
 0.678571 
 0.372533 
 0.826792 
 0.0591832
 0.556892 
 0.108039 
 0.153758 
 0.692473 
 0.485299 

### Cartesian vs Linear indexing

Some array types support efficiently indexing via a "linearized" single index. Depending on the representation, other array types may need to convert back and forth between Cartesian `(i,j,...)` index tuples and scalar linear indices. This relies on integer division which is much more expensive than multiplication and addition!

In [25]:
@show size(a)
a[2500] # linear indexing

size(a) = (1000,1000)


0.4361198481868407

In [26]:
?ind2sub

search: ind2sub



```
ind2sub(dims, index) -> subscripts
```

Returns a tuple of subscripts into an array with dimensions `dims`, corresponding to the linear index `index`.

**Example**:

```
i, j, ... = ind2sub(size(A), indmax(A))
```

provides the indices of the maximum element.

```
ind2sub(a, index) -> subscripts
```

Returns a tuple of subscripts into array `a` corresponding to the linear index `index`.


In [27]:
?sub2ind

search: sub2ind



```
sub2ind(dims, i, j, k...) -> index
```

The inverse of `ind2sub`, returns the linear index corresponding to the provided subscripts.


In [28]:
ind2sub(size(a), 2500)

(500,3)

In [29]:
sub2ind(size(a), 500, 3)

2500

### Copying Arrays

In [30]:
a = [1, 2, 3, 4]

4-element Array{Int64,1}:
 1
 2
 3
 4

In [31]:
b = a

4-element Array{Int64,1}:
 1
 2
 3
 4

In [32]:
b[1] = 10

10

In [33]:
a

4-element Array{Int64,1}:
 10
  2
  3
  4

This might shock users from a certain popular programming language! This also means that the value of an array is its pointer to the memory location. To actually create another copy of an array use the `copy()` function

In [34]:
c = copy(a)

4-element Array{Int64,1}:
 10
  2
  3
  4

In [35]:
c[1] = 1

1

In [36]:
a

4-element Array{Int64,1}:
 10
  2
  3
  4

Let us go deeper one level, 

In [37]:
a = Vector{Vector{Float64}}(3)
a[1] = [1;2;3]
a[2] = [1;2]
a[3] = [3;4;5]
a

3-element Array{Array{Float64,1},1}:
 [1.0,2.0,3.0]
 [1.0,2.0]    
 [3.0,4.0,5.0]

In [38]:
b = a

3-element Array{Array{Float64,1},1}:
 [1.0,2.0,3.0]
 [1.0,2.0]    
 [3.0,4.0,5.0]

In [39]:
b[1] = [1, 4, 5]
a

3-element Array{Array{Float64,1},1}:
 [1.0,4.0,5.0]
 [1.0,2.0]    
 [3.0,4.0,5.0]

In [40]:
b = copy(a)

3-element Array{Array{Float64,1},1}:
 [1.0,4.0,5.0]
 [1.0,2.0]    
 [3.0,4.0,5.0]

In [41]:
b[1] = [1,2,3]
a

3-element Array{Array{Float64,1},1}:
 [1.0,4.0,5.0]
 [1.0,2.0]    
 [3.0,4.0,5.0]

`copy` did not help here, this is because `copy()` is only a shallow copy. Use `deepcopy()` which not only copies the outer structure but also recursively copies the internal structures too.

In [42]:
c = deepcopy(a)

3-element Array{Array{Float64,1},1}:
 [1.0,4.0,5.0]
 [1.0,2.0]    
 [3.0,4.0,5.0]

### Operations on Arrays

#### Array methods

In [43]:
a = [1, -2, 3, 0]

4-element Array{Int64,1}:
  1
 -2
  3
  0

In [44]:
length(a)

4

In [45]:
sum(a)

2

In [46]:
mean(a)

0.5

In [47]:
std(a)

2.0816659994661326

In [48]:
var(a)

4.333333333333333

In [49]:
b = sort(a, rev=true)

4-element Array{Int64,1}:
  3
  1
  0
 -2

#### Matrix operations

In [50]:
a = ones(1, 2)

1×2 Array{Float64,2}:
 1.0  1.0

In [51]:
b = ones(2, 2)

2×2 Array{Float64,2}:
 1.0  1.0
 1.0  1.0

In [52]:
a * b

1×2 Array{Float64,2}:
 2.0  2.0

To solve the linear system `A X = B` for `X` use `A \ B`

In [53]:
A = [1 2; 2 3]

2×2 Array{Int64,2}:
 1  2
 2  3

In [54]:
B = ones(2, 2)

2×2 Array{Float64,2}:
 1.0  1.0
 1.0  1.0

In [55]:
A \ B

2×2 Array{Float64,2}:
 -1.0  -1.0
  1.0   1.0

In [56]:
inv(A) * B

2×2 Array{Float64,2}:
 -1.0  -1.0
  1.0   1.0

Although the last two operations give the same result, the first one is numerically more stable and should be preferred in most cases

#### Elementwise operations

In [57]:
ones(2, 2) * ones(2, 2) # This results in regular matrix multiplication

2×2 Array{Float64,2}:
 2.0  2.0
 2.0  2.0

In [58]:
ones(2, 2) .* ones(2, 2) # This results in elementwise multiplication

2×2 Array{Float64,2}:
 1.0  1.0
 1.0  1.0

In [59]:
a = [10, 0, 30]

3-element Array{Int64,1}:
 10
  0
 30

In [60]:
b = [-100, 0, 100]

3-element Array{Int64,1}:
 -100
    0
  100

In [61]:
b .> a

3-element BitArray{1}:
 false
 false
  true

In [62]:
a .== b

3-element BitArray{1}:
 false
  true
 false

#### Conditional extraction

In [63]:
a = randn(4)

4-element Array{Float64,1}:
  0.637778
  0.183411
 -1.97616 
  0.330595

In [64]:
a .< 0

4-element BitArray{1}:
 false
 false
  true
 false

In [65]:
a[a .< 0]

1-element Array{Float64,1}:
 -1.97616

#### Vectorised functions

In [66]:
log(ones(4))

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

In [67]:
[log(x) for x in ones(4)] # Obtain similar results using comprehension

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

#### Map operation using anonymous functions

In [68]:
map((x)->2*x,1:10)

10-element Array{Int64,1}:
  2
  4
  6
  8
 10
 12
 14
 16
 18
 20

#### Broadcast

Julia offers broadcast(), which expands singleton dimensions in array arguments to match the corresponding dimension in the other array without using extra memory, and applies the given function elementwise:

In [69]:
 a = rand(2,1)

2×1 Array{Float64,2}:
 0.878821
 0.784896

In [70]:
A = rand(2,3)

2×3 Array{Float64,2}:
 0.584032  0.356916  0.261547
 0.38572   0.819347  0.576612

In [71]:
broadcast(+, a, A)
#@show vec(a)
#@show typeof(vec(a))
#broadcast(+, vec(a), A)

2×3 Array{Float64,2}:
 1.46285  1.23574  1.14037
 1.17062  1.60424  1.36151

In [72]:
A = 1:5
B = [2;3;4;5;6]

5-element Array{Int64,1}:
 2
 3
 4
 5
 6

In [73]:
C = reverse(B)

5-element Array{Int64,1}:
 6
 5
 4
 3
 2

In [74]:
A.*B.*C

5-element Array{Int64,1}:
 12
 30
 48
 60
 60